# --- !Ups

CREATE TABLE "USERS"(
    "ID" SERIAL NOT NULL PRIMARY KEY,
    "MAIL" VARCHAR NOT NULL UNIQUE,
    "PASSWORD" VARCHAR NOT NULL UNIQUE,
    "NAME" VARCHAR NOT NULL UNIQUE,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL
);

CREATE TRIGGER UPDATE_TRIGGER BEFORE UPDATE ON "USERS" FOR EACH ROW
EXECUTE PROCEDURE SET_UPDATE_TIME();

CREATE TRIGGER CREATE_TRIGGER BEFORE INSERT ON "USERS" FOR EACH ROW
EXECUTE PROCEDURE SET_CREATE_TIME();


# --- !Downs

DROP TABLE IF EXISTS  "USERS";
