# --- !Ups

CREATE TABLE "USER_REGISTRATION_REQUESTS"(
    "REQUEST_KEY" VARCHAR NOT NULL PRIMARY KEY,
    "MAIL" VARCHAR NOT NULL,
    "EXPIRED_AT" TIMESTAMP NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL
);


CREATE TRIGGER UPDATE_TRIGGER BEFORE UPDATE ON "USER_REGISTRATION_REQUESTS" FOR EACH ROW
EXECUTE PROCEDURE SET_UPDATE_TIME();

CREATE TRIGGER CREATE_TRIGGER BEFORE INSERT ON "USER_REGISTRATION_REQUESTS" FOR EACH ROW
EXECUTE PROCEDURE SET_CREATE_TIME();

# --- !Downs

DROP TABLE IF EXISTS  "INVITE_USER_MAILS";